--Este archivo debe tener como nombre data-tipobbdd para que spring sepa cogerlo y ejecutarlo
INSERT INTO AUTHOR (ID, FIRST_NAME,LAST_NAME) VALUES (1,'EDU','MERCHAN');
INSERT INTO POST (ID,TITLE,BODY,AUTHOR_ID,POSTED_ON) VALUES (1,'EMPEZANDO','EMPEZANDO CON SPRING',1,CURRENT_DATE ());
INSERT INTO POST (ID,TITLE,BODY,AUTHOR_ID,POSTED_ON) VALUES (2,'CONTINUANDO','CONTINUANDO CON SPRING',1,CURRENT_DATE ());